# HOW DOES COMPUTER READS IMAGES

- Every coloured image is distributed into 3d matrices, each element of which represent the intensity of brightness. 
- these matrices (coloured) have 3 channels. R G B.
- If there's a black and white image has 1 channel
- 100x100 means 100 rows and 100 rows and respectively 3 or 1 channel based on colour.


IN OPENCV THE IMAGE IS FIRST CONVERTED TO A NUMPY ARRAY. 

In [2]:
import cv2

#READING AN IMAGE(COLOURED)

#1 for coloured and 0 for black and white

img=cv2.imread("dog.jpeg",1)   #coloured
#print(img)
#type(img)
#print(img.shape) #194rows , 259coloumns, 3channels

#DISPLAY IMAGE
"""
cv2.imshow("dog.jpeg", img)  #OPENS A WINDOW TO DISPLAY IMAGE

cv2.waitKey(2000)                #WINDOW WAITS FOR 2000 milliseconds to close

cv2.destroyAllWindows()     
"""

#if we don't declare destroyAllWindows, the window will stop responding after nemtioned time.

#cleans the window on the basis of parameter of waitforkey function\

#RESIZING

"""
resized=cv2.resize(img, (600,600))
cv2.imshow("dog.jpeg",resized)
cv2.waitKey(2000)
cv2.destroyAllWindows()
"""


#RESIZING SYMETRICALLY

#Here we are making the size of the image just DOUBLE

resized_img=cv2.resize(img, (int(img.shape[1]*2), int(img.shape[0]*2)))   

cv2.imshow("dog",resized_img)
cv2.waitKey(2000)
cv2.destroyAllWindows()



# HOW DOES FACE RECOGNITION WORKS.

- Load an image that has face.
- Create a cascade classifier that contains the features of the face
- Search for the row and column value of the face numpy array ( THE COORDINATES OF THE FACE RECT lANGLE) 
- Display the image with the rectangular face box.



In [8]:
import cv2

face_cascade=cv2.CascadeClassifier("C:\opencv\sources\data\haarcascades\haarcascade_frontalface_default.xml")

#read the image
photo=cv2.imread("1.jpeg")

gray=cv2.cvtColor(photo, cv2.COLOR_BGR2GRAY)

#identifying the coordinates of face 

faces=face_cascade.detectMultiScale(gray, scaleFactor=1.05, minNeighbors=5)
print(type(faces))
print(faces)

#creating rectangle around for the coordinates.

for x,y,w,h in faces:
    photo= cv2.rectangle(photo, (x,y), (x+w, y+h), (57, 3, 252), 3)
    
resized = cv2.resize(photo,(int(photo.shape[1]), int(photo.shape[0])))

cv2.imshow("FACE RECOGNITION", photo)

cv2.waitKey(20000)

cv2.destroyAllWindows()

<class 'numpy.ndarray'>
[[ 18 283  63  63]
 [303  72 100 100]
 [ 73 169  40  40]]


# CAPTUIRNG FIRST FRAME OUT OF A VIDEO

In [9]:
import cv2
import time

#to create a Video_capture object
video=cv2.VideoCapture(0)

#WE'LL ADD A WINDOW THAT'LL SHOW THE VIDEO

check, frame=video.read()

#check is a bool datatype that will return true if it is able to read the object or the frame being captured.

#adding time for the camera to be on

print(check)
print(frame)

time.sleep(3)

#now we will add the imshow function

cv2.imshow("capture",frame)

cv2.waitKey(2000)

cv2.destroyAllWindows()

#releasing the video

video.release()

# UNTILL HERE IF WE RUN, WE'll SEE THAT WEBCAM LIGHT BLINKS.

# NOW WE'LL ADD A TIME DELAY UP THERE.





True
[[[169 162 143]
  [169 162 143]
  [169 161 138]
  ...
  [145 148 119]
  [146 147 123]
  [146 147 123]]

 [[167 160 141]
  [166 159 140]
  [169 161 138]
  ...
  [144 147 118]
  [146 147 123]
  [145 146 122]]

 [[171 160 140]
  [173 162 142]
  [176 165 138]
  ...
  [144 145 121]
  [145 146 124]
  [145 146 124]]

 ...

 [[186 178 143]
  [185 177 142]
  [178 172 137]
  ...
  [165 157 136]
  [165 157 136]
  [162 154 133]]

 [[182 175 143]
  [183 176 144]
  [178 171 139]
  ...
  [165 157 134]
  [166 158 137]
  [164 156 135]]

 [[183 176 144]
  [182 175 143]
  [176 171 140]
  ...
  [166 158 135]
  [166 158 135]
  [164 156 133]]]


# CAPTURING THE VIDEO

THE LOGIC IS:
- in order to capture a video, we will be usig a 'WHILE' loop. While the condition will be such that, untill unless 'CHECK' is true, Python will display frames.

In [ ]:
import cv2
import time

video = cv2.VideoCapture(0)

a=1

while True:
    a=a+1
    check, frame = video.read()
    print(frame)
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    cv2.imshow("CAPTURE",gray)
    
    key = cv2.waitKey(1)    #new frame after 1 millisecond
    
    if key == ord('q'):         #press q to close the windows
        break
        
print(a)   #THIS WILL PRINT THE NUMBER OF FRAMES

video.release()

cv2.destroyAllWindows()